### ISSUE TITLE
Zswap

### ISSUE THREAD

**Issue by GSchuemann** [themagicalmammal/howtolinux#28]
Hello there, 

I recently learned about Zswap and thought it might be a nice addition for this guide, as it is (or rather might be) a performance improvement for PCs with low RAM. According to some sources I could find ZSWAP should be used instead of ZRAM, when there is a swap-file/partition on the disk. And ZRAM when you have no swap at all. I couldn't seem to find any clear answer which one is faster and I doubt there is any, I guess it depends on the machine and workload/used applications. 

Some more things on enabling them and really basic usage:
ZRAM 
Once you have installed zram-config, you can start it manually with `sudo systemctl start zram-config`. And the correct command to test if it's working should be `zramctl` instead of `cat /proc/swaps`. If you use a swap im addition to ZRAM  you should adjust   `swapiness` to 80-100 and `page-cache` to 0. Source for that: https://github.com/ecdye/zram-config
Documentation: https://www.kernel.org/doc/html/latest/admin-guide/blockdev/zram.html?highlight=zram

ZSWAP
It can be enabled with `echo 1 | sudo tee /sys/module/zswap/parameters/enabled` and then reboot. 
Documentation:
https://www.kernel.org/doc/html/latest/admin-guide/mm/zswap.html?highlight=zswap

For both different compression algorithms can be used, I guess I would stick with the default ones, but a good comparison can be found [here](https://github.com/facebook/zstd#benchmarks).

**Comment by themagicalmammal** [comment]
There is also profile-sync-daemon which makes a browser very fast. I have been busy lately when I get time I am thinking of making a website on this that will be on github.

**Comment by themagicalmammal** [comment]
And I have shifted to Void linux and I will make this thing more universal.
